eLearning/eLearn/urls.py
"""Defines URL patterns for eLearn."""

from django.urls import path
from . import views

app_name = "eLearn"

urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    path('main/', views.main, name='main'),
]

eLearning/elearning/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('eLearn.urls')),
    path('users/', include('users.urls')),
]

eLearning/users/urls.py
"""Defines URL patterns for users"""

from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = "users"

urlpatterns = [
    # Login page
    path('login/',
         auth_views.LoginView.as_view(template_name='users/login.html'),
         name='login'),

    # Logout page
    path('logout/', views.logout_view, name='logout'),

    # Registration page
    path('register/', views.register, name='register'),
]

eLearning/eLearn/models.py
from django.db import models

eLearning/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from users.choices import *

class CustomUser(AbstractUser):
    # add additional fields in here
    userType = models.IntegerField("User role", choices=USER_TYPES, default=1)

    def __int__(self):
        return self.userType

    def __str__(self):
        return self.email

    def __str__(self):
        return self.first_name

    def __str__(self):
        return self.last_name

eLearning/users/forms.py
# users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm):
        model = CustomUser
        fields = ('username', 'userType', 'first_name', 'last_name', 'email')

class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('username', 'userType', 'first_name', 'last_name', 'email')

eLearning/eLearn/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

def index(request):
    """The home page for eLearning"""
    return render(request, 'eLearn/index.html')

@login_required
def main(request):
    """The main page for eLearning"""
    return render(request, 'eLearn/main.html')

eLearning/users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import login, logout, authenticate
#from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .forms import CustomUserCreationForm
from django.contrib.auth import views as auth_views

def logout_view(request):
    """Log the user out."""
    logout(request)
    return HttpResponseRedirect(reverse('eLearn:index'))

def register(request):
    """Register a new user."""
    if request.method != 'POST':
        # Display blank registration form.
        form = CustomUserCreationForm()
    else:
        # Process completed form.
        form = CustomUserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # Log the user in and then redirect to home page.
            authenticated_user = authenticate(username=new_user.username,
                password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('eLearn:main'))

    context = {'form': form}
    return render(request, 'users/register.html', context)

eLearning/eLearn/templates/eLearn/base.html
{% load bootstrap4 %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>eLearning</title>
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
    <link rel="stylesheet" type="text/css" href="{% static 'eLearn/style.css' %}">
    <script src="{% static 'eLearn/sidebar.js' %}"></script>

  </head>

  <body>

    <!-- Static navbar -->
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'eLearn:index' %}">eLearning</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-end" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          {% if user.is_authenticated %}
            <div class="nav-item nav-link active">Hello, {{ user.username }}.</div>
            <a class="nav-item nav-link" href="{% url 'users:logout' %}">log out<span class="sr-only">(current)</span></a>
          {% else %}
            <a class="nav-item nav-link" href="{% url 'users:register' %}">register</a>
            <a class="nav-item nav-link" href="{% url 'users:login' %}">log in</a>
          {% endif %}
        </div>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="page-header mt-5">
        {% block header %}{% endblock header %}
      </div>
      <div>
        {% block content %}{% endblock content %}
      </div>
    </div> <!-- /container -->

  </body>
</html>

eLearning/eLearn/templates/eLearn/index.html
{% extends "eLearn/base.html" %}

{% block header %}
  <div class="container">
    <div class="jumbotron">
      <h1>Learning made easy.</h1>
    </div>
  </div>
{% endblock header %}

{% block content %}
  <div class="container">
    <h2>eLearning facilitates the flow of instructional information from a professor to their students.</h2>
  </div>
{% endblock content %}

eLearning/eLearn/templates/eLearn/main.html
{% extends "eLearn/base.html" %}

{% block header %}
{% endblock header %}
{% block content %}

<div class="container-fluid">
<div class="row">
  <div class="col-9">
    <div class="tab-content" id="v-pills-tabContent">
      <div class="tab-pane fade show active" id="v-pills-home" role="tabpanel" aria-labelledby="v-pills-home-tab">
        <div class="embed-responsive embed-responsive-16by9">
          <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/1oHax_k0i44" allowfullscreen></iframe>
        </div>
      </div>
      <div class="tab-pane fade" id="v-pills-profile" role="tabpanel" aria-labelledby="v-pills-profile-tab">
        <div class="embed-responsive embed-responsive-16by9">
          <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/eaIV7kInUc0" allowfullscreen></iframe>
        </div>
      </div>
      <div class="tab-pane fade" id="v-pills-messages" role="tabpanel" aria-labelledby="v-pills-messages-tab">
        <div class="embed-responsive embed-responsive-16by9">
          <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/yx7wOxtf80E" allowfullscreen></iframe>
        </div>
      </div>
      <div class="tab-pane fade" id="v-pills-settings" role="tabpanel" aria-labelledby="v-pills-settings-tab">
        <div class="embed-responsive embed-responsive-16by9">
          <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/jd5AEjeE_CY" allowfullscreen></iframe>
        </div>
      </div>
    </div>
  </div>
  <div class="col-3">
    <div class="nav flex-column nav-pills red" id="v-pills-tab" role="tablist" aria-orientation="vertical">
      <a class="nav-link active" id="v-pills-home-tab" data-toggle="pill" href="#v-pills-home" role="tab" aria-controls="v-pills-home" aria-selected="true">Introduction</a>
      <a class="nav-link" id="v-pills-profile-tab" data-toggle="pill" href="#v-pills-profile" role="tab" aria-controls="v-pills-profile" aria-selected="false">Camping 101</a>
      <a class="nav-link" id="v-pills-messages-tab" data-toggle="pill" href="#v-pills-messages" role="tab" aria-controls="v-pills-messages" aria-selected="false">Canoe Trip</a>
      <a class="nav-link" id="v-pills-settings-tab" data-toggle="pill" href="#v-pills-settings" role="tab" aria-controls="v-pills-settings" aria-selected="false">In the Wild</a>
    </div>
  </div>
</div>
</div>

{% endblock content %}

eLearning/eLearn/templates/eLearn/videoplay.html
{% block contents %} 
    <video name='demo' controls autoplay width='50%' height='40%'> 
    <source src="{{STATIC_URL}}sample1.mp4" type="video/mp4"></source> 
    </video> 
{% endblock %}

eLearning/users/templates/users/login.html
{% extends "eLearn/base.html" %}
{% load  bootstrap4 %}

{% block header %}

  <div class="container">
    <h2>Log in to your account.</h2>
  </div>

{% endblock header %}
{% block content %}

  <div class="container">
    <form method="post" action="{% url 'users:login' %}" class="form">
      {% csrf_token %}

      {% bootstrap_form form %}

      {% buttons %}
        <button name="submit" class="btn btn-primary">log in</button>
      {% endbuttons %}

      <input type="hidden" name="next" value="{% url 'eLearn:main' %}" />
    </form>
  </div>

{% endblock content %}

eLearning/users/templates/users/register.html
{% extends "eLearn/base.html" %}
{% load bootstrap4 %}

{% block header %}

  <div class="container">
    <h2>Register a new eLearning account.</h2>
  </div>

{% endblock header %}
{% block content %}

  <div class="container">
    <form method="post" action="{% url 'users:register' %}" class="form">
      {% csrf_token %}

      {% bootstrap_form form %}

      {% buttons %}
        <button name="submit" class="btn btn-primary">register</button>
      {% endbuttons %}

      <input type="hidden" name="next" value="{% url 'eLearn:index' %}" />
    </form>
  </div>

{% endblock content %}